# Site settings
title: Robotics Club @ UCSB
email: ucsbroboticsclub@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  [Description goes here]
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ucsbroboticsclub.github.io" # the base hostname & protocol for your site
github_username:  ucsbroboticsclub

collections:
  projects:
    output: true
    permalink: /projects/:path/

# Build settings
markdown: kramdown

exclude: [README.md, Gemfile, Gemfile.lock]

